swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8443'
basePath: /
paths:
  /signup/proposal:
    post:
      tags:
        - sign-up-resource
      summary: saveNaturalPerson
      operationId: saveNaturalPersonUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: body
          required: true
          schema:
            $ref: '#/definitions/NaturalPersonDTO'
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: uuid
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/signup/proposal/{document}/address':
    post:
      tags:
        - sign-up-resource
      summary: saveAddressNaturalPerson
      operationId: saveAddressNaturalPersonUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: body
          required: true
          schema:
            $ref: '#/definitions/AddressDTO'
        - name: document
          in: path
          description: document
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: uuid
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/signup/proposal/{document}/address/{uuid}/photography':
    post:
      tags:
        - sign-up-resource
      summary: savePhotographyNaturalPerson
      operationId: savePhotographyNaturalPersonUsingPOST
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: document
          in: path
          description: document
          required: true
          type: string
        - name: img
          in: formData
          description: img
          required: true
          type: file
        - name: uuid
          in: path
          description: uuid
          required: true
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          schema:
            type: boolean
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  AddressDTO:
    type: object
    properties:
      addressComplement:
        type: string
      city:
        type: string
      district:
        type: string
      neighborhoods:
        type: string
      street:
        type: string
      zipCode:
        type: string
    title: AddressDTO
  NaturalPersonDTO:
    type: object
    properties:
      dateBirth:
        type: string
        format: date
      document:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
    title: NaturalPersonDTO
